#+TITLE: Bin scripts
#+AUTHOR: Jeff Carlson

* Preface

Some useless scripts I wrote.

* Installation

#+BEGIN_SRC shell
  mkdir $HOME/bin
  for i in [a-z]* ; do
      cp $i $HOME/bin/
  done
#+END_SRC

* Contents

** colors.sh

An extremely over-engineered display of the 256-color palate.

** fed-up.sh

Fedora Upgrade script based on [[https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/][DNF System Upgrade]].  This needs to be
run as root.

** iptnum.awk

#+BEGIN_SRC shell
  iptables-save | iptnum.awk
#+END_SRC

** nsurl.sh

Have you ever seen an article on some website (perhaps on your phone)
and you wanted to read it later when you were at your desk?  Just
=ssh= back to your desktop at home and pass the URL to this script.
It will leave a link (using =notify-send=) to the URL waiting on your
desktop for your return.

** reader.pl

Display text with very long lines in an outdented format.  Requires
the Perl Text::Tabs+Wrap package.

Here's an example to make the output of opkg easier to read.

#+BEGIN_SRC shell
  ssh openwrt opkg list > /tmp/opkg.list
  reader.pl /tmp/opkg.list | less
#+END_SRC

** spa.py

*Single Packet Authentication*

Send an SPA packet to a pknock-protected Linux firewall.  Requires the
Python Crypto.Hash module.

** ssh-menu.sh

Reads your =known_hosts= files and builds an ncurses menu of hosts to
select as ssh destinations.

** xssh-menu.sh

Same as ssh-menu.sh, but launches a zenity GUI to pick a host.  Set a
TERMINAL environment variable to launch something other than xterm.
